### ISSUE TITLE
fantastic

### ISSUE THREAD

**Issue by ClarkGuan** [bbqsrc/cargo-ndk#17]
![image](https://user-images.githubusercontent.com/7122493/107046801-018a5b80-6802-11eb-91db-ca3559db805f.png)

![image](https://user-images.githubusercontent.com/7122493/107047009-4adaab00-6802-11eb-95f0-1c59d9b15bba.png)

**Comment by bbqsrc** [comment]
It is intriguing to me that you have taken screenshots of text, perhaps to mitigate censorship on a platform? Github doesn't do that.

In any case, I will keep this simple: people who are this rude to me are not invited to my hot pot parties, and trust me, they're fucking good my friend. 😄 

It reminds me that I need to update the README though. More [recently corroborated information](https://www.bbc.com/news/world-asia-china-55794071):

> Women in China's "re-education" camps for Uighurs have been systematically raped, sexually abused, and tortured, according to detailed new accounts obtained by the BBC. 

And that's just the lede.

@ClarkGuan: it's easy to dismiss me as "the evil white man", sure. But we're talking about documented cases of actual genocide here. There's a reason the entire world knows what happened in Tiananmen Square on July 4, 1989 but nobody in China does. Indoctrination and censorship is how the Chinese government functions.

I've worked with and drank with Uyghur people and Han people. I like both :smile:. You would do yourself some justice to love your fellow country people instead of putting them into camps and believing that everyone is a terrorist just because the state-owned media tells you so. 😉 

---
And for future viewers of this issue wondering why this is even in the README? Mainland Chinese people disproportionately follow and use this codebase relative to any other repository that I maintain.

Github is one of the few websites accessible in mainland China that is hosted in the US, which means that unfiltered text is communicable. Given this unique context, I see it as a responsible action to enable as many people as possible to be aware of that which is happening around them.

**Comment by ClarkGuan** [comment]
Since you have Chinese and Uighur friends, I will reply in Chinese. They may be able to translate it for you, just to see the difference between the first-hand information and the transferred information：

1. 或许你认为美国的公司打造的平台很公平没有审查，但请容许其他人对此保留观点，毕竟这是一个曾经限制伊朗等国人民使用的平台，仅仅因为某些莫名其妙的理由。
2. 你如果来自五眼联盟国家或者土耳其，这个 issue 我提都不会提。
3. 你可以问问你的新疆朋友，维吾尔族一共有多少人。新闻标题动不动就用 `million` 字眼……真的，相信我，有点智商的人都觉得可笑。
4. 我从来没有说过我们的政府多么正义，而且它们的确限制我们获取国外的信息。但是请相信，中国的人不像你想的那样（好像什么都不知道的傻子），至少我会通过我获取到的信息去分析、论证，来得出我的观点。
5. 对不起，89年的事儿我略知一二，甚至我怀疑你并不比我知道的多多少，但我不会像你那样义正言辞的下结论，的确有点儿键盘侠的味道。
6. 实话说我真的很讨厌你的言语，那种居高临下的感觉，好像自己掌握了所有的真理，而且你引述的 BBC 报道 —— 我的天，真的有人完完全全相信这个事情，而且丝毫不怀疑。
7. 如果你真的对政治感兴趣，我觉得你可以详细的了解一下前因后果。中国有句老话 “兼听则明，偏信则暗”，送给你。
